name: Add mod to database
description: Request for a new mod to be added to the database.
title: "[Your mod name here]"
labels: ["add-mod"]
assignees:
  - Raicuparta
body:
  - type: input
    id: name
    attributes:
      label: Mod name
      description: Human-readable title for your mod. If you want to change your mod's name later, you'll need to request a change to the database again.
      placeholder: Outer Wilds Mod Template
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: GitHub repository URL
      description: GitHub repository that contains the mod's source code and releases.
      placeholder: https://github.com/Raicuparta/ow-mod-template
    validations:
      required: true
  - type: input
    id: uniqueName
    attributes:
      label: Mod uniqueName
      description: "Your mod's ID, unique within the whole database. IMPORTANT: must match uniqueName from your mod's manifest.json."
      placeholder: Raicuparta.ModTemplate
    validations:
      required: true
  - type: input
    id: parent
    attributes:
      label: Parent uniqueName
      description: If this mod is an addon for another mod, place the parent's uniqueName here. For instance, custom planets made with New Horizons would have `xen.NewHorizons` in this field.
      placeholder: Raicuparta.ModTemplateParent
  - type: dropdown
    attributes:
      label: Utility mod dropdown
      description: A mod is a utility only if it isn't useful by itself, and only serves as a dependency for other mods.
      options:
        - Yes
        - No
  - type: checkboxes
    id: utility
    attributes:
      label: Utility mod
      description: Check only if this mod isn't useful by itself, and only serves as a dependency for other mods.
      options:
        - label: Utility mod
