name: Add mod to database
description: Request for a new mod to be added to the database.
title: "[Your mod name here]"
labels: ["add-mod"]
assignees:
  - Raicuparta
body:
  - type: input
    id: name
    attributes:
      label: Mod name
      description: Human-readable title for your mod. If you want to change your mod's name later, you'll need to request a change to the database again.
      placeholder: Outer Wilds Mod Template
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: GitHub repository
      description: GitHub repository that contains the mod's source code and releases.
      placeholder: Raicuparta/ow-mod-template
    validations:
      required: true
  - type: input
    id: uniqueName
    attributes:
      label: Mod uniqueName
      description: "Your mod's ID, unique within the whole database. IMPORTANT: must match uniqueName from your mod's manifest.json."
      placeholder: Raicuparta.ModTemplate
    validations:
      required: true
