name: "Get mods"
description: "Gets mod releases"
inputs:
  mods:
    description: "JSON list of mods to check"
    required: true
    default: "[]"
  github-token:
    description: "Token for GitHub authentication"
    required: true
  discord-hook-url:
    description: "Secret Discord hook url with token"
    required: true
  secrets:
    description: "All workflow secrets"
    required: true
outputs:
  releases:
    description: "JSON list of latest mod releases"
runs:
  using: "node16"
  main: "build/index.js"
