name: Discord notification
on:
  pull_request:
    types: [closed]
concurrency: "main"
jobs:
  discord_notification:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'add-mod') && github.event.pull_request.merged == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Test discord hook
        uses: fjogeleit/http-request-action@master
        with:
          url: "${{ secrets.DISCORD_HOOK_URL }}"
          method: "POST"
          data: '{ "embeds": [{ "title": "${{ github.event.pull_request.title }}", "url": "${{ github.event.pull_request.html_url }}" }] }'
