name: Handle New Mod Submission
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  setup:
    if: ${{ contains(github.event.issue.labels.*.name, 'add-mod') }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: stefanbuck/github-issue-praser@v2
        id: issue
        with:
          template-path: .github/ISSUE_TEMPLATE/add-mod.yml

      - run: echo ${{ toJson(steps.issue.outputs.jsonString) }}
