name: PR from Issue
on:
  issues:
    types: [opened, reopened]
concurrency: "main"
jobs:
  pr_from_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add-mod.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}'

      - name: Get local Mod Database file
        id: local-mods
        run: echo "::set-output name=mods::$(< ./mods.json sed ':a;N;$!ba;s/\n/ /g')"

      - uses: pnpm/action-setup@v2
        with:
          version: 6.23.6
          run_install: true
      - name: Build
        run: |
          cd create-pr
          pnpm run build

      - name: Create PR from issue
        id: create-pr
        uses: ./create-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN  }}
          form: "${{ steps.issue-parser.outputs.jsonString }}"
          mods: "${{ steps.local-mods.outputs.mods }}"

      - name: Write mods list to file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: mods.json
          contents: "${{ steps.create-pr.outputs.mods }}"
          write-mode: overwrite

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Add ${{fromJSON(steps.issue-parser.outputs.jsonString).name}}"
          body: "${{fromJSON(steps.issue-parser.outputs.jsonString).repo}}"
