name: PR from Issue
on:
  issues:
    types: [opened, reopened]
concurrency: 'main'
jobs:
  pr_from_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - uses: stefanbuck/github-issue-praser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add-mod.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}'
