name: Upload PR artifact
on:
  pull_request:
    branches:
      - "source"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2
        with:
          version: 6.23.6
          run_install: true

      - name: Build
        run: |
          cd scripts
          pnpm run build

      - name: Checkout database repo
        uses: actions/checkout@v3
        with:
          ref: master
          path: database

      - name: Remove existing thumbnails
        run: rm -rf database/thumbnails

      - name: Fetch mod releases and manifests
        uses: ./actions/update-database
        with:
          out-directory: output
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN  }}
          mods: mods.json
          previous-database: database/database.json
          google-service-account: "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}"

      - uses: actions/upload-artifact@v3
        with:
          name: database-preview
          path: output
